package com.supersharetask.downloadmanager.utils

const val KEY_DOWNLOAD_ID = "DOWNLOAD_ID"
const val KEY_DOWNLOAD_ACTION = "DOWNLOAD_ACTION"
const val ACTION_DOWNLOAD_START = "DOWNLOAD_START"
const val ACTION_DOWNLOAD_STOP = "DOWNLOAD_STOP"
const val ACTION_BROADCAST_DOWNLOAD_PROGRESS = "ACTION_BROADCAST_DOWNLOAD_PROGRESS"
const val PARAM_BROADCAST_DOWNLOAD_PROGRESS = "PARAM_BROADCAST_DOWNLOAD_PROGRESS"
